scripts:
    - name: Upgrade dependencies
    script: flutter pub upgrade
    - name: Flutter clean
    script: flutter clean
    - name: Install dependencies
    script: flutter pub get
    - name: Build Android APK
    script: flutter build apk --release