name: sum_grid_app
description: A simple Sum Grid game
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
url_launcher: ^6.2.5
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true